### ISSUE TITLE
oauth_callback 400 Bad Request

### ISSUE THREAD

**Issue by ylcnky** [IfcOpenShell/ifcopenshell-jupyterhub#1]
Hi, thanks for this nice work.
I setup the server and notebook, and access the login page. However, after authentication with Github credentials I receive `400 : Bad Request OAuth callback made without a code`
The Authorization callback URL in Github in settings is like `https://mydomain.com/hub/oauth_callback`
Should I change the `c.GitHubOAuthenticator.oauth_callback_url` in `jupyterhub_config.py`?
Due to the Docker-based installation, I assume not to touch config file.
Otherwise, what should be the Authorization callback URL ? Thanks.

**Comment by ylcnky** [comment]
OK, Instead of the `jupyterhub_config.py` file located in `root` of server, when I modified the one inside docker (`/var/lib/docker/overlay2/...`), the problem resolved.

**Comment by aothms** [comment]
If I understand you correctly you were trying to update the settings after everything was already setup? Good to have this as a reference, but probably easiest is to always start clean and edit `secrets/oauth.env` and `make notebook_image` during the setup procedure.
