### ISSUE TITLE
s.set(s.USE_PYTHON_OPENCASCADE, True)

### ISSUE THREAD

**Issue by raouajaraib** [IfcOpenShell/ifcopenshell-jupyterhub#3]
I'm a new user of ifcopenshell, I'm trying to visualise the geometry of an ifc, so I tried your code (visualize.py) and I have this error message that I can't understand.
`AttributeError                            Traceback (most recent call last)
<ipython-input-30-24e404fff641> in <module>()
      4 
      5 s = ifcopenshell.geom.settings()
----> 6 s.set(s.USE_PYTHON_OPENCASCADE, True)
      7 geometry = dict((f[item.data.id], (item.geometry, item.styles)) for item in ifcopenshell.geom.iterator(s, f))
      8 

/home/jaraib/pythonpackages/ifcopenshell/ifcopenshell_wrapper.pyc in <lambda>(self, name)
     95     __setattr__ = lambda self, name, value: _swig_setattr(self, settings, name, value)
     96     __swig_getmethods__ = {}
---> 97     __getattr__ = lambda self, name: _swig_getattr(self, settings, name)
     98     __repr__ = _swig_repr
     99     WELD_VERTICES = _ifcopenshell_wrapper.settings_WELD_VERTICES

/home/jaraib/pythonpackages/ifcopenshell/ifcopenshell_wrapper.pyc in _swig_getattr(self, class_type, name)
     72 
     73 def _swig_getattr(self, class_type, name):
---> 74     return _swig_getattr_nondynamic(self, class_type, name, 0)
     75 
     76 

/home/jaraib/pythonpackages/ifcopenshell/ifcopenshell_wrapper.pyc in _swig_getattr_nondynamic(self, class_type, name, static)
     67         return method(self)
     68     if (not static):
---> 69         return object.__getattr__(self, name)
     70     else:
     71         raise AttributeError(name)

AttributeError: type object 'object' has no attribute '__getattr__'`

Thank you for your help

**Comment by aothms** [comment]
This is probably more issue about https://github.com/IfcOpenShell/IfcOpenShell/ but can you explain what version of IfcOpenShell you are using and how did you install it.

You also need to have pythonOCC installed. Preferably through conda. https://github.com/tpaviot/pythonocc-core
